/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ndk_ndkpro_JNIManager */

#ifndef _Included_com_ndk_ndkpro_JNIManager
#define _Included_com_ndk_ndkpro_JNIManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ndk_ndkpro_JNIManager
 * Method:    callNativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ndk_ndkpro_JNIManager_callNativeMethod
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
